//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaret
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider
    {
        public int SlideID { get; set; }
        public string ResimYolu { get; set; }
        public string Baslik { get; set; }
        public string Fiyat { get; set; }
        public string Mesaj { get; set; }
        public Nullable<int> link { get; set; }
        public Nullable<bool> aktif { get; set; }
    }
}
