//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaret
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yetkilendirme
    {
        public int Y_ID { get; set; }
        public int UyeID { get; set; }
        public int YetkiID { get; set; }
    
        public virtual Uyeler Uyeler { get; set; }
        public virtual Yetki Yetki { get; set; }
    }
}
